### ISSUE TITLE
Answer command sometimes is not interpreted

### ISSUE THREAD

**Issue by LeoSaucedo** [LeoSaucedo/rikka-bot#72]
![Screenshot_20210717-163108](https://user-images.githubusercontent.com/5789689/126048743-efc7828b-304e-4a9f-bc17-b91c49e68418.jpg)

The answer command is sometimes not triggered when a user attempts to answer an active trivia question. Normal behavior always prompts a response from the bot, whether it is correct or not, and in the attached example no message was returned.

We must investigate why the answer isn't returning and what we can do to resolve it.

**Comment by andrew-bass** [comment]
Fixed this issue here: https://github.com/LeoSaucedo/rikka-bot/commit/dad085e3fa862fbf28afbf30c70699932e52b3b5
