### ISSUE TITLE
Give Points Command

### ISSUE THREAD

**Issue by LeoSaucedo** [LeoSaucedo/rikka-bot#77]
Implement a `;give points <user> <amount>` command with the following spec:
- If a user's balance >= `amount`, give `amount` points to `user`.
- If a user's balance < `amount`, throw an error.
- Function must use `Economy.addPoints` and not implement another function.

**Comment by KueZie** [comment]
@LeoSaucedo Does this need to check for admin privileges as a part of the spec?

**Comment by LeoSaucedo** [comment]
> @LeoSaucedo Does this need to check for admin privileges as a part of the spec?

No. Any user can give their points to any other user.
