### ISSUE TITLE
View Other User's Inventory

### ISSUE THREAD

**Issue by LeoSaucedo** [LeoSaucedo/rikka-bot#79]
Implement `;inv <user>` with the following spec:

- If the parameter mentioned is a valid user, display their inventory.
- If the parameter is not a valid user, throw an error.
- Must use existing `getInventory` functions.

**Comment by bryandean80** [comment]
added here https://github.com/LeoSaucedo/rikka-bot/pull/83/commits/9277c738845ebad12ac1b0696dc27cec31067ab7
